provisioning:
  enabled: true
  topics:
    - name: cve
      partitions: 6
      replicationFactor: 3
  postScript: |
    echo "Custom provisioning started"
    curl -X POST http://localhost:15000/quitquitquit
    echo "Custom provisioning complete"
broker:      
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 50Gi
  resourcesPreset: "large"
  readinessProbe:
    initialDelaySeconds: 60

controller:      
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 100Gi
  resourcesPreset: "large"
  readinessProbe:
    initialDelaySeconds: 5

listeners:
  client:
    protocol: plaintext
  controller:
    protocol: plaintext
  interbroker:
    protocol: plaintext
  external:
    protocol: plaintext
  extraListeners: []

networkPolicy:
  enabled: false

metrics:
  jmx:
    enabled: true
    kafkaJmxPort: 5555
    image:
      registry: docker.io
      repository: bitnami/jmx-exporter
      tag: 1.0.1-debian-12-r5
      pullPolicy: IfNotPresent
    containerPorts:
      metrics: 5556
    service:
      ports:
        metrics: 5556
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
        prometheus.io/path: "/metrics"
    config: |-
      jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
      lowercaseOutputName: true
      lowercaseOutputLabelNames: true
      ssl: false
      whitelistObjectNames: ["kafka.controller:*", "kafka.server:*", "java.lang:*", "kafka.network:*", "kafka.log:*"]