provisioning:
  enabled: true
  topics:
    - name: cve
      partitions: 6
      replicationFactor: 3
broker:      
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 50Gi
  resourcesPreset: "xlarge"
  readinessProbe:
    initialDelaySeconds: 60
  autoscaling:
    hpa:
      enabled: true
      minReplicas: 3
      maxReplicas: 6

controller:      
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 100Gi
  resourcesPreset: "xlarge"
  readinessProbe:
    initialDelaySeconds: 5
  autoscaling:
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 3

listeners:
  client:
    protocol: plaintext
  controller:
    protocol: plaintext
  interbroker:
    protocol: plaintext
  external:
    protocol: plaintext
  extraListeners: []