provisioning:
  enabled: true
  topics:
    - name: cve
      partitions: 6
      replicationFactor: 3
broker:      
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 50Gi
  resourcesPreset: "large"
  readinessProbe:
    initialDelaySeconds: 60

controller:      
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 100Gi
  resourcesPreset: "large"
  readinessProbe:
    initialDelaySeconds: 5

listeners:
  client:
    protocol: plaintext
  controller:
    protocol: plaintext
  interbroker:
    protocol: plaintext
  external:
    protocol: plaintext
  extraListeners: []