alertmanager:
  enabled: false

server:
  global:
    scrape_interval: 10s
  scrape_configs:
    - job_name: 'kubernetes'
      kubernetes_sd_configs:
        - role: node
        - role: pod
        - role: service
    - job_name: 'kafka'
      static_configs:
        - targets: ['kafka-broker-headless.ns2.svc.cluster.local:5556'] 
    - job_name: 'postgres'
      static_configs:
        - targets: ['postgres-exporter-prometheus-postgres-exporter.monitoring.svc.cluster.local:9187']