{
 "title": "Flask App Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Queries in the Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "increase(queries_total[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logins in the Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "increase(logins_total[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Signups in the Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "increase(signups_total[24h])", "legendFormat": "__auto" }
   ]
  }
 ]
}